services:
  my_sql:
    image: mysql:9
    container_name: my_sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: oreshkinem
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PORT: 3306
    volumes:
      - ./sakila-db/sakila-schema.sql:/docker-entrypoint-initdb.d/01-sakila-schema.sql
      - ./sakila-db/sakila-data.sql:/docker-entrypoint-initdb.d/02-sakila-data.sql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    restart: unless-stopped
#    tty: true
#    stdin_open: true


